'use strict';

const BUILTIN_PATTERNS = Object.freeze([
  {
    rule_name: 'eval_call',
    category: 'dynamic-exec',
    severity: 'risk',
    regex: '\\beval\\s*\\(',
    reminder: 'Dynamic code execution via eval(). Avoid evaluating runtime strings; parse data explicitly.',
  },
  {
    rule_name: 'new_function',
    category: 'dynamic-exec',
    severity: 'risk',
    regex: 'new\\s+Function\\s*\\(',
    reminder: 'new Function() evaluates strings as code. Replace with explicit logic or a safe parser.',
  },
  {
    rule_name: 'node_child_process_exec',
    category: 'dynamic-exec',
    severity: 'risk',
    regex: 'child_process\\.(exec|execSync)\\s*\\(',
    reminder: 'Shell exec of a string is injection-prone. Prefer execFile/spawn with an argv array.',
  },
  {
    rule_name: 'python_os_system',
    category: 'dynamic-exec',
    severity: 'risk',
    regex: '\\bos\\.system\\s*\\(',
    reminder: 'os.system runs a shell command string. Use subprocess.run([...]) with a list, shell=False.',
  },
  {
    rule_name: 'python_subprocess_shell',
    category: 'dynamic-exec',
    severity: 'risk',
    regex: 'subprocess\\.(call|run|Popen|check_output)\\s*\\([^)]*shell\\s*=\\s*True',
    reminder: 'subprocess with shell=True is injection-prone. Pass an argument list and shell=False.',
  },
  {
    rule_name: 'python_pickle_load',
    category: 'unsafe-deserialization',
    severity: 'risk',
    regex: '\\bpickle\\.loads?\\s*\\(',
    reminder: 'pickle deserialization executes arbitrary code on untrusted input. Use json or a safe format.',
  },
  {
    rule_name: 'yaml_unsafe_load',
    category: 'unsafe-deserialization',
    severity: 'risk',
    regex: 'yaml\\.load\\s*\\((?![^)]*Safe)',
    reminder: 'yaml.load without SafeLoader can instantiate arbitrary objects. Use yaml.safe_load.',
  },
  {
    rule_name: 'php_unserialize',
    category: 'unsafe-deserialization',
    severity: 'risk',
    regex: '\\bunserialize\\s*\\(',
    reminder: 'unserialize() on untrusted input enables object injection. Use json_decode for data.',
  },
  {
    rule_name: 'react_dangerously_set_inner_html',
    category: 'dom-injection',
    severity: 'risk',
    substrings: ['dangerouslySetInnerHTML'],
    reminder: 'dangerouslySetInnerHTML can introduce XSS. Sanitize input or render as text.',
  },
  {
    rule_name: 'dom_inner_html_assignment',
    category: 'dom-injection',
    severity: 'risk',
    regex: '\\.innerHTML\\s*=',
    reminder: 'Assigning to .innerHTML with untrusted data is an XSS vector. Use textContent or sanitize.',
  },
  {
    rule_name: 'dom_document_write',
    category: 'dom-injection',
    severity: 'risk',
    regex: 'document\\.write\\s*\\(',
    reminder: 'document.write with dynamic input enables XSS. Build DOM nodes explicitly instead.',
  },
  {
    rule_name: 'github_workflow_edit',
    category: 'workflow-file',
    severity: 'warn',
    path_only: true,
    paths: ['**/.github/workflows/**'],
    reminder: 'Workflow files can grant repository-level permissions. Review trigger and permission scope.',
  },
  {
    rule_name: 'private_key_block',
    category: 'hardcoded-secret',
    severity: 'risk',
    regex: '-----BEGIN (?:RSA |EC |OPENSSH |DSA |PGP )?PRIVATE KEY-----',
    reminder: 'Hardcoded private key material. Load keys from a secret manager, never from source.',
  },
  {
    rule_name: 'aws_access_key_id',
    category: 'hardcoded-secret',
    severity: 'risk',
    regex: '\\b(?:AKIA|ASIA)[0-9A-Z]{16}\\b',
    reminder: 'Hardcoded AWS access key id. Move credentials to the secret manager / environment.',
  },
  {
    rule_name: 'stripe_live_secret',
    category: 'hardcoded-secret',
    severity: 'risk',
    substrings: ['sk_live_'],
    reminder: 'Hardcoded live Stripe secret key prefix. Load credentials from the secret manager.',
  },
  {
    rule_name: 'generic_secret_assignment',
    category: 'hardcoded-secret',
    severity: 'warn',
    regex: '(?:password|passwd|secret|api[_-]?key|access[_-]?token|auth[_-]?token)\\s*[:=]\\s*[\'"][^\'"\\s]{8,}[\'"]',
    reminder: 'Looks like a hardcoded credential. Load it from configuration / a secret manager instead.',
  },
]);

module.exports = { BUILTIN_PATTERNS };
